service: serverless-express-boilerplate
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, "eu-north-1"}
  stage: ${opt:stage, "dev"}
  # enable tracing
  tracing:
    lambda: true
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-plugin-tracing
  - serverless-offline

functions:
  api:
    handler: index.handler
    timeout: 10
    events:
      - httpApi: ANY /
      - httpApi: ANY /{proxy+}